### ISSUE TITLE
Fig4 in Paper

### ISSUE THREAD

**Issue by jw9603** [yeeeqichen/FiTs#2]
Hi. 

I am really interested in reading your paper.

In the leftmost illustration of Fig4, does the red node represent QA context and the fluorescent(yellow) and green node represent Question/Answer nodes?

Thank you.

**Comment by yeeeqichen** [comment]
Hi, Jiwon

Thanks for your attention for our paper. The nodes in the leftmost illustration of Fig.4 all represent nodes in the knowledge graph. This part wants to illustrate that the QA supervision loss takes the subgraph of KG as part of its input and uses the correct answer as the supervision signal to optimize the model. It somehow lacks of taking the fine-grained information between the textual information (i.e., the question and the candidate answer) and the graph information (i.e., the nodes in the subgraph) into consideration. So we propose the KSD loss as well as KBR loss to help the model to efficiently and effectively reason with both sources of knowledge.

Hope this could answer your question! If you have any further questions, feel free to contact us.

Best.

**Comment by jw9603** [comment]
Thank you for your reply.
